### ISSUE TITLE
예제로 배우는 스프링 입문

### ISSUE THREAD

**Issue by EzKorry** [EzKorry/spring-summer#2]
https://www.inflearn.com/course/spring_revised_edition

**Comment by EzKorry** [comment]
## 문제

- 우리가 직접 객체를 만들어서 Bean으로 등록하지 않아도, IoC 컴포넌트가 만들어질 때 스프링이 알아서 Bean으로 만들어야 하는 객체를 우리 코드에서 찾아서 등록하는 과정 설명하시오.

- `@Autowired` 를 사용할 수 있는 세 곳은 어디이고, 이곳 중 가장 권장되는 것은 무엇이고 그 이유는 무엇인가?

- service abstraction 을 썼을 때 장점 두가지는?

- 프록시 패턴이란 무엇인가?

- DB에서 트랜잭션 처리란 무엇인가?

**Comment by hasterprin** [comment]
의존성 주입DI이란?

aop를 구현하는 세 가지 방법과 그 중 spring이 채택한 방법은?

scope란 무엇이며 ioc컨테이너의 default scope는?

jvm내에서 bean 으로 등록된 클래스의 인스턴스를 2개 이상 생성할 수 있는가?

spring 로그 설정파일은?

**Comment by EzKorry** [comment]
> 의존성 주입DI이란?
> 
> aop를 구현하는 세 가지 방법과 그 중 spring이 채택한 방법은?
> 
> scope란 무엇이며 ioc컨테이너의 default scope는?
> 
> jvm내에서 bean 으로 등록된 클래스의 인스턴스를 2개 이상 생성할 수 있는가?
> 
> spring 로그 설정파일은?

1.  의존성 주입DI이란?

    일종의 IoC임. IoC는 제어의 역전이란 말로, 어떤 클래스가 다루는 작업에 대해서 그 클래스 내에 새로운 객체를 만들어 온전히 제어하면서 작업할 수 있지만, 이렇게 되면 의존성이 커져서 어플리케이션 개발이 유연해지지 못하게 된다. 그래서 클래스 내에서 새로운 객체를 만드는 대신, 생성자를 통해 의존성을 밖에서 관리할 수 있도록 하여 제어권을 역전시키는 것이다. 이것처럼 밖에서 안으로 의존성을 주입시키는 방법이 DI임.

1.  aop를 구현하는 세 가지 방법과 그 중 spring이 채택한 방법은?

    1. 컴파일 단계에서 바이트코드를 만들 때 소스코드에 추가 코드를 얹인 바이트코드가 만들어지도록 함. (AspectJ 사용)
    2. 바이트코드에서 실제 프로그램 동작인 메모리로 코드가 옮겨갈 때 코드가 추가되도록 함 (AspectJ 사용)
    3. 코드 상에서 프록시 패턴(디자인 패턴 중 하나)을 이용함. 같은 인터페이스 I를 가진 다른 클래스 `A`와 `AProxy`가 있을 때, `AProxy`가 하는 일은 단지 `A`에서 추가적인 작업을 하는 것일 뿐이지만, 클라이언트 코드 입장에서는 같은 인터페이스 `I`를 쓰는 것처럼 사용가능함. (`A`를 쓰는 것처럼 `AProxy`를 쓸 수 있음.)

1. scope란 무엇이며 ioc컨테이너의 default scope는?

    스프링에서 다루는 객체인 Bean의 유효 범위를 뜻함. `singleton`이 기본 값인데, `singleton`은 ioc 컨테이너 내에 인스턴스가 하나만 존재함. 그 외에 `prototype`은 여러 인스턴스가 존재할 수 있고, Spring MVC Web Application 에서만 사용되는 `request`, `session`, `global session` 등이 있다.


1. jvm내에서 bean 으로 등록된 클래스의 인스턴스를 2개 이상 생성할 수 있는가?
    jvm 내에 IoC Container가 여러 개면 singleton 스코프로 선언된 Bean도 여러 개 생성할 수 있지 않을까????ㅋㅋㅋ IoC 컨테이너 안에서는 singleton Bean은 하나밖에 못함.

1. 로그 설정 파일!

    `src/main/resources/application.properties` 에서 `logging.level.org.springframework.web=DEBUG`라고 설정한다.

**Comment by hasterprin** [comment]
1. 우리가 직접 객체를 만들어서 Bean으로 등록하지 않아도, IoC 컴포넌트가 만들어질 때 스프링이 알아서 Bean으로 만들어야 하는 객체를 우리 코드에서 찾아서 등록하는 과정 설명하시오.
> 컴포넌트 등록 방법은 annotation스캔과 applicationContext.xml파일을 스캔하는 두 종류가 있음. 그 중 요새 쓰는 annotation스캔은 기본적인 @Component를 중심으로 세분화된 세 개의 어노테이션(@Controller @Service @Repository)이 bean으로 등록됨.

2.  @Autowired 를 사용할 수 있는 세 곳은 어디이고, 이곳 중 가장 권장되는 것은 무엇이고 그 이유는 무엇인가?
> 생성자, 필드, setter가 있음. 생성자가 제일 권장되는데 이유는 인스턴스 생성에 필요한 하위 레퍼런스를 강제로 생성하게 할 수 있음. 

3.  service abstraction 을 썼을 때 장점 두가지는?
> 유튭 정리 안대잇어서 구글링함 ㅋㅋ
특정 기술을 내부에 숨기고 개발자에게 편의성을 제공. 
 다양한 기술스택을 바꿔서 사용할 수 있음 ex) @transactional 은 jdbc, hibernate, jpa 를 가리지 않고 사용가능

4. 프록시 패턴이란 무엇인가?
> 실제 서비스를 직접 호출하지 않고 중간 대리자 역할을 끼워넣는 패턴. 기존의 클래스를 변경하지 않고 추가적인 코드와 기존의 클래스를 호출하고자 하는 목적. 일반적으로 기존 클래스와 프록시 상위에 인터페이스를 두고 메소드 이름을 기존 클래스와 프록시 클래스를 같게하여 구현함. 

5. DB에서 트랜잭션 처리란 무엇인가?
> 2개 이상의 DML문을 처리할 때 최소한의 논리적 단위를 지정하기 위함임. DB특징인 원자성에 부합하는 기능임. 보통 all or nothing이라고 하드라고. 암튼 이기종 DB도 가능하고 하나의 DB도 가능. 일반적으론 JDBC사용할 떄 XAConnectionPool사용, autocommit (false) 하고 끝날 때 commit하면 알아서 commit, rollback해주는 데 spring에서는 @transactional 만 쓰면 알아서 해줘서 개편함.

**Comment by hasterprin** [comment]
4 번 니말대로 ioc컨테이너 여러개 만들어도 되고 걍 new해서 생성하면 ioc컨테이너 밖에 만들어지기도 하고 아니면 prototype scope설정하면 된다드라 ㅋㅋㅋ 첨알고 신기해서 내봄

**Comment by hasterprin** [comment]
1. Spring Oauth2 에서 Resource Owner, client, Resource Server, Authorization Server 네 가지 역할 및 관계를 설명하라

2. csrf란?

3. 인증과정에서 cors설정이 필요한 이유는?

**Comment by EzKorry** [comment]
답 정확하네욤~~~!
